@baseUrl = http://localhost:3001/api

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMzY5OTQ0NDdkYjhhMjQ1MDlmMTdjOSIsImlhdCI6MTU5NzQxNjM1Mn0.jIGevHdhFkYrDz-Cl4M4eqRnG3p4FvMqR25NyzyY1lA

{
    "title": "React",
    "author": "Michael Chan",
    "url": "https://reac.com/",
    "likes": 15
}

###################################

DELETE {{baseUrl}}/blogs/5f36b5287d907838c84eb552
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZjM2YjVmOTdkOTA3ODM4Yzg0ZWI1NTMiLCJpYXQiOjE1OTc0MjExMDZ9.XQuG3XajdnKliIJWmXomplQ_wnESh7KBPGSOgMCYec4

###################################

PUT {{baseUrl}}/blogs/5f09b01bd4fc8820383f66eb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMzY2MjY4OWY0ZDRiMDVkNDk5MjNkNSIsImlhdCI6MTU5NzQwMjg2Nn0.FJtg7odiHnQLdMTQa5I7v1jrJI3Ta7vKW2yWs7-lVBI

{
   
}

###################################

POST {{baseUrl}}/users
Content-Type: application/json

{
   "username": "admin",
   "name": "Steven",
   "password": "Fish"
}

###################################

POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "Fish"
}