@baseUrl = http://localhost:3001/api

POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMzY3NzIxOTlmYzViM2IzODAyYmQyYSIsImlhdCI6MTU5NzQwNDk3OH0.HyG2Qj2SrW0WtZMYaXHMjDUqo_cX92M8us1Qo6Pd5fs

{
    "title": "React",
    "author": "Michael Chan",
    "url": "https://reac.com/",
    "likes": 15
}

###################################

DELETE {{baseUrl}}/blogs/

###################################

PUT {{baseUrl}}/blogs/5f09b01bd4fc8820383f66eb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMzY2MjY4OWY0ZDRiMDVkNDk5MjNkNSIsImlhdCI6MTU5NzQwMjg2Nn0.FJtg7odiHnQLdMTQa5I7v1jrJI3Ta7vKW2yWs7-lVBI

{
   
}

###################################

POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "root",
    "password": "sekret"
}