@baseUrl = http://localhost:3001/api/persons

POST {{baseUrl}}
Content-Type: application/json

{
    "name": "Hello",
    "number": "12343"
}

######################

GET {{baseUrl}}/5f061077e5674a08c8cc713d


######################

PUT {{baseUrl}}/5f0989d27887551448719dd6
Content-Type: application/json

{
    "name": "Christopher",
    "number": "8971345354"
}