@baseUrl = http://localhost:3001/api/persons

POST {{baseUrl}}
Content-Type: application/json

{
    "name": "He",
    "number": "123512532"
}

######################

GET {{baseUrl}}/5f061077e5674a08c8cc713d


######################

PUT {{baseUrl}}/5f0f43108f646816c8fd5a6e
Content-Type: application/json

{
    "name": "Hello",
    "number": "12354736556"
}